# Generated by Django 2.0.3 on 2018-03-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assettype', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=200)),
                ('purchasedate', models.DateTimeField(verbose_name='purchased date')),
                ('price', models.FloatField(default=0)),
                ('document', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('locationType', models.CharField(choices=[('st', 'Storage'), ('fl', 'Flat'), ('gr', 'Garage'), ('ho', 'House'), ('ba', 'Bank'), ('oth', 'Other')], default='ho', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('clientno', models.CharField(max_length=200)),
                ('purchasedate', models.DateTimeField(verbose_name='purchased date')),
                ('document', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeinventory.User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeinventory.Location'),
        ),
    ]
