# Generated by Django 2.0.3 on 2018-03-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeinventory', '0004_auto_20180327_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
